module.exports = {
  recipe: require("./apiController/recipe"),
  auth: require("./user/auth"),
  login: require("./user/login"),
  logout: require("./user/logout"),
  signup: require("./user/signup"),
  signout: require("./user/signout"),
  createFood: require("./myfrigo/createFood"),
  updateFood: require("./myfrigo/updateFood"),
  deleteFood: require("./myfrigo/deleteFood"),
  updateMypage: require("./mypage/updateMypage"),
  myfrigoFood: require("./myfrigo/myfrigoFood"),
  getPost: require("./post/getPost"),
  createPost: require("./post/createPost"),
  updatePost: require("./post/updatePost"),
  deletePost: require("./post/deletePost"),
  createComment: require("./comment/createComment"),
  updateComment: require("./comment/updateComment"),
  deleteComment: require("./comment/deleteComment"),
  like: require("./post/like"),
  google: require("./oauth/google"),
};
